on:
  push:
    branches:
    - dev
    - dev/*
    - development
    - development/*
    - feature/*
    - chore/*
    tags:
    - 'authopts/v[0-9]+.[0-9]+.[0-9]+'
    paths:
    - 'authopts/**'
    - '!authopts/**.md'
    - '!authopts/scripts/**'
  pull_request:
    branches:
    - main
    paths:
    - 'authopts/**'
    - '!authopts/**.md'
    - '!authopts/scripts/**'


jobs:
  test:
    strategy:
      matrix:
        version: [ '1.20', '1.21', '1.22' ]
        os: [ ubuntu-latest' ]
    defaults:
      run:
        working-directory: authopts
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
        cache-dependency-path: |
          authopts/go.sum
    
    - name: Download dependencies
      run: go get
    
    - name: Test
      run: go vet ./... && go test -v ./...

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/authopts/v') }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create release
      run: gh release create $TAG --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}
