name: Update authopts
on:
  release:
    types:
    - created

jobs:
  update:
    name: Update authopts
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    defaults:
      run:
        working-directory: authopts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b chore/update-dependencies-azcfg-$TAG
      env:
        TAG: ${{ github.ref_name }}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: |
          authopts/go.sum

    - name: Update dependencies 
      run: |
        go get -u github.com/KarlGW/azcfg@$TAG
        go get -u github.com/Azure/azure-sdk-for-go/sdk/azcore
        go get -u github.com/google/go-cmp
        go mod tidy
      env:
        TAG: ${{ github.ref_name }}

    - name: Create pull request
      run: |
        git add go.mod go.sum
        git commit -m "chore(authopts): update dependency to azcfg@$TAG"
        git push -u origin chore/update-dependencies-azcfg-$TAG
        gh pr create \
          --title "chore(authopts): update dependency to azcfg@$TAG" \
          --base main \
          --body "This pull request updates the dependency to azcfg@$TAG."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}
